// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa3Mk9V3dnMNn3iWyfawESH_XayEx7Lb0',
    appId: '1:549640564957:web:e941e72d6ebd8ab8366b34',
    messagingSenderId: '549640564957',
    projectId: 'coffee-app-1cf8d',
    authDomain: 'coffee-app-1cf8d.firebaseapp.com',
    storageBucket: 'coffee-app-1cf8d.firebasestorage.app',
    measurementId: 'G-NWS1Q1872T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkwhS11Bv3TZcMJ6NlxP-SHj4DLSrr7-A',
    appId: '1:549640564957:android:5a9ad5abf9bd3f3e366b34',
    messagingSenderId: '549640564957',
    projectId: 'coffee-app-1cf8d',
    storageBucket: 'coffee-app-1cf8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8ehBBaWl9f0ly9kPfGgSC1sj0DXu69yg',
    appId: '1:549640564957:ios:c029e0a01c13eb41366b34',
    messagingSenderId: '549640564957',
    projectId: 'coffee-app-1cf8d',
    storageBucket: 'coffee-app-1cf8d.firebasestorage.app',
    iosBundleId: 'com.example.coffeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8ehBBaWl9f0ly9kPfGgSC1sj0DXu69yg',
    appId: '1:549640564957:ios:c029e0a01c13eb41366b34',
    messagingSenderId: '549640564957',
    projectId: 'coffee-app-1cf8d',
    storageBucket: 'coffee-app-1cf8d.firebasestorage.app',
    iosBundleId: 'com.example.coffeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa3Mk9V3dnMNn3iWyfawESH_XayEx7Lb0',
    appId: '1:549640564957:web:b123eed7fb1fd14b366b34',
    messagingSenderId: '549640564957',
    projectId: 'coffee-app-1cf8d',
    authDomain: 'coffee-app-1cf8d.firebaseapp.com',
    storageBucket: 'coffee-app-1cf8d.firebasestorage.app',
    measurementId: 'G-L9K2SFNWWC',
  );
}
